import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Application } from "./application/component/Application";
import { NavBar } from "./shared/navbar/component/NavBar";
import { Footer } from "./shared/footer/component/Footer";
import { UbicacionState } from "./application/component/ubicaciones/context/ubicacion.state";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <NavBar></NavBar>
            <Application>
            </Application>
            <Footer></Footer>
      </body>
    </html>
  );
}
